### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry-community/brooklyn-service-broker#2]
I want to install Brooklyn service broker, as it was described in this [tutorial][1]. After cloning the repo I run `gradle clean build` and it fails with an error:

```
FAILURE: Build failed with an exception.

A problem occurred evaluating root project 'brooklyn-service-broker'.
> org.gradle.api.tasks.TaskContainer.create(Ljava/lang/String;Ljava/lang/Class;)Lorg/gradle/api/Task;
```

If re-run this task with `--debug` option I see [NoSuchMethod exception][2].

My environment:

```
$ gradle -v

------------------------------------------------------------
Gradle 1.4
------------------------------------------------------------

Gradle build time: Monday, September 9, 2013 8:44:25 PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.8.0_40 (Oracle Corporation 25.40-b25)
OS: Linux 3.13.0-43-generic amd64
```

[1]: http://www.cloudsoftcorp.com/blog/2015/02/integrating-cloud-foundry-apache-brooklyn-part-1-service-broker/
[2]: https://gist.github.com/lexsys27/c500dd15573dbe676e39

**Comment by robertgmoss** [comment]
Have you installed Apache Brooklyn?

git clone git@github.com:apache/incubator-brooklyn.git
cd incubator-brooklyn
mvn clean install -DskipTests

**Comment by lexsys27** [comment]
It is compiling now. Do I need to compile SB on the same host as Apache Brooklyn installed?

I thought it is runtime dependency.

**Comment by robertgmoss** [comment]
no you don't need to run it there, it's just that the service broker has a dependency on Brooklyn's client library in the snapshot version which you need to in able to build it.  By running mvn install, you are putting that dependency into your local maven repo.

**Comment by lexsys27** [comment]
Oh! Hard to guess this)

I managed to get Brooklyn compiled and running, 

```
[INFO] BUILD SUCCESS

Started Brooklyn console at http://127.0.0.1:8081/
```

but still have the same error.

Maybe the problem is in Java version? I use Oracle Java 6u45 for building Brooklyn and Oracle Java 8u40 for building SB.

**Comment by robertgmoss** [comment]
I don't think so, the wrong java version usually complains about unsupported major.minor version.
Could be a gradle or groovy thing?

$ gradle -v

------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_31 (Oracle Corporation 25.31-b07)
OS:           Linux 3.13.0-46-generic amd64

**Comment by lexsys27** [comment]
I have update my Gradle and Groovy environment to latest versions.

```
$ gradle -v

------------------------------------------------------------
Gradle 2.3
------------------------------------------------------------

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.6.0_45 (Sun Microsystems Inc. 20.45-b01)
OS:           Linux 3.13.0-43-generic amd64
```

SB was more specific this time:

```
* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not find org.apache.brooklyn:brooklyn-rest-client:0.7.0-SNAPSHOT
```

The problem is that I used Brooklyn `0.7.0-M2-incubating`.

**Comment by robertgmoss** [comment]
that's why I got you to get Brooklyn from github and compile it to your local maven repo - did you get it from the Brooklyn website instead?

**Comment by lexsys27** [comment]
Yes, the previous version was from the site as I want to actually run it.

Now I am compiling from GitHub as you advised.

**Comment by robertgmoss** [comment]
you should be able to use `0.7.0-M2-incubating` as your running Brooklyn, it's just you have to compile the service broker with the snapshot version

**Comment by lexsys27** [comment]
Am I right that I need different Java versions for compiling both? Java 6 for Brooklyn and Java 8 for SB?

**Comment by robertgmoss** [comment]
No, you can compile Brooklyn with Java 8 if you wish, but Service Broker must use Java 8.  That's because the [Parent project](https://github.com/cloudfoundry-community/spring-boot-cf-service-broker) uses it.

**Comment by lexsys27** [comment]
Ok, now I have built brooklyn form snapshot. SB prints following error during compilation:

```
/home/ubuntu/work/brooklyn-service-broker/src/main/java/org/cloudfoundry/community/servicebroker/brooklyn/service/BrooklynServiceInstanceBindingService.java:6: cannot access org.cloudfoundry.community.servicebroker.exception.ServiceBrokerException
bad class file: org/cloudfoundry/community/servicebroker/exception/ServiceBrokerException.class(org/cloudfoundry/community/servicebroker/exception:ServiceBrokerException.class)
class file has wrong version 52.0, should be 50.0
```

**Comment by lexsys27** [comment]
Actually, I had an error while compiling Brooklyn with Java 8:

```
Compilation failure:
[ERROR] no more tokens - could not parse error message: Annotation processing got disabled, since it requires a 1.6 compliant JVM
```

After downgrading java to 6u45 Brooklyn compiles normally. So I end up with bi-java environment on poor ubuntu node :)

**Comment by robertgmoss** [comment]
weird, I compile Brooklyn with Java 8

**Comment by robertgmoss** [comment]
regarding SB error - are you sure javac and java are using java 8?

**Comment by robertgmoss** [comment]
I've got the following and that is sufficient to compile both Brooklyn and SB: 

    $ javac -version
    javac 1.8.0_31

    $ java -version
    java version "1.8.0_31"
    Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by lexsys27** [comment]
Great! SB is finally compiling without errors.

```
BUILD SUCCESSFUL
```

Last problem was in gradle using java 6.

Thank you for help, Robert!

**Comment by lexsys27** [comment]
I will come tomorrow with pull request documenting detailed prerequisites for building SB on clean Ubuntu 14.04 machine.

Also I will try to build Brooklyn with Java 8u40 as it is more convenient to use one version for all the stuff.

**Comment by robertgmoss** [comment]
great, thanks!

**Comment by lexsys27** [comment]
The results of Brooklyn compilation with Java 8.

`0.7.0-SNAPSHOT` compilation OK.

`0.7.0-M2-incubating` compilation fails.
